version: '3.8'

services:
  stripe-payment-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules