version: '3.8'

services:
  stripe-payment-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # Add your Stripe keys here
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:-pk_test_your_key}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_your_key}
    restart: unless-stopped